const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let visibleUnitNames=[];
const renderPointsBadge=Profiles.renderPointsBadge, renderPointsDetail=Profiles.renderPointsDetail;
function renderUnits(){const selectedList=ArmyLists.load().state.lists.find(list=>list.id===$('#unitListFilter').value);const inList=u=>!selectedList||selectedList.units.some(entry=>entry.name===u.name);const query=norm($('#unitSearch').value.trim()),cat=$('#unitCategory').value;const additional=ADDITIONAL_POINT_UNITS.filter(u=>inList(u)&&(cat==='all'||u.category===cat)&&(!query||norm(JSON.stringify(u)).includes(query)));$('#additionalPoints').hidden=!additional.length;$('#additionalPointsGrid').innerHTML=additional.map(u=>`<article class="additional-point-card">${renderPointsDetail(u,u.name)}<button type="button" class="small-button point-profile-button" data-extra-name="${esc(u.name)}">Abrir costes y añadir a lista →</button></article>`).join('');const list=units.filter(u=>inList(u)&&(cat==='all'||u.category===cat)&&(!query||norm(JSON.stringify(u)).includes(query)));visibleUnitNames=[...list,...additional].map(u=>u.name);$('#unitCount').textContent=units.length;$('#unitResults').textContent=`${list.length} ${list.length===1?'ficha':'fichas'}${additional.length?` · ${additional.length} ${additional.length===1?'unidad adicional con puntos':'unidades adicionales con puntos'}`:''}`;$('#unitEmpty').hidden=!!(list.length+additional.length);$('#unitGrid').innerHTML=list.map((u,i)=>`<button class="unit-card" data-index="${units.indexOf(u)}"><div class="unit-image"><img src="images/${u.photo}.jpeg" alt=""><span>${esc(u.category)}</span></div><div class="unit-card-body"><small>FOTO ${u.photo} · PÁG. ${esc(u.page)}</small><h2>${esc(u.name)}</h2>${renderPointsBadge(u)}<div class="mini-stats">${['M','T','SV','W','LD','OC','INV'].map((k,n)=>`<span><i>${k}</i><b>${esc(u.stats[n])}</b></span>`).join('')}</div><p>${esc(u.weapons.slice(0,2).map(w=>w[0]).join(' · '))}</p><div class="unit-link">ABRIR FICHA <b>+</b></div></div></button>`).join('');$('#additionalPointsGrid').querySelectorAll('[data-extra-name]').forEach(button=>button.onclick=()=>Profiles.openUnit(button.dataset.extraName,{listId:$('#unitListFilter').value==='all'?null:$('#unitListFilter').value,entries:visibleUnitNames.map(name=>({name,key:name}))}));$('#unitGrid').querySelectorAll('.unit-card').forEach(b=>b.onclick=()=>openUnit(units[Number(b.dataset.index)]))}

const openUnit=u=>Profiles.openUnit(u.name,{listId:$('#unitListFilter').value==='all'?null:$('#unitListFilter').value,entries:visibleUnitNames.map(name=>({name,key:name}))});
const savedLists=ArmyLists.load().state.lists;
$('#unitListFilter').innerHTML+=savedLists.map(list=>`<option value="${esc(list.id)}">${esc(list.name)}</option>`).join('');
function applyCompact(compact){$('#unitGrid').classList.toggle('is-compact',compact);$('#unitViewToggle').setAttribute('aria-pressed',compact);$('#unitViewToggle').textContent=compact?'Vista de tarjetas':'Vista compacta';}
try{applyCompact(localStorage.getItem('custodes.profile-view')==='compact')}catch{}
$('#unitViewToggle').onclick=()=>{const compact=!$('#unitGrid').classList.contains('is-compact');applyCompact(compact);try{localStorage.setItem('custodes.profile-view',compact?'compact':'cards')}catch{}};
$('#unitListFilter').addEventListener('change',renderUnits);
$('#unitSearch').addEventListener('input',renderUnits);$('#unitCategory').addEventListener('change',renderUnits);document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#profileDialog').open){e.preventDefault();$('#unitSearch').focus()}});renderUnits();Profiles.openFromHash();
