const units=[
 {name:'Shield-Captain (Allarus)',category:'Infantería',photo:'01',page:'107',stats:['7"','8','2+','9','5+','2','4+'],core:'Deep Strike · Leader',rules:['Master of the Armoury: una vez por ronda, si no está preparado puede usar una habilidad de datasheet.','Archeotech Teleport-shunter: puede redesplegarse a reservas estratégicas.'],composition:'1 Shield-Captain in Allarus Terminator Armour',keywords:'INFANTRY · CHARACTER · IMPERIUM · TERMINATOR',weapons:[['Ballistus Grenade Launcher','18"','3','2+','5','-1','1'],['Castellan Axe · ranged','24"','2','2+','5','-1','2'],['Guardian Spear · ranged','24"','2','2+','5','-1','2'],['Castellan Axe · melee','Melee','5','2+','10','-2','4'],['Guardian Spear · melee','Melee','8','2+','8','-2','2']]},
 {name:'Shield-Captain (Dawneagle Jetbike)',category:'Montada',photo:'01',page:'107',stats:['12"','8','2+','10','5+','2','4+'],core:'Deep Strike · Leader',rules:['Master of the Ka’tahs: una vez por ronda, recupera una habilidad de datasheet.','Sweeping Advance: puede avanzar y retirarse con mayor movilidad.'],composition:'1 Shield-Captain on Dawneagle Jetbike',keywords:'MOUNTED · CHARACTER · FLY · IMPERIUM · SHIELD-CAPTAIN',weapons:[['Hurricane Bolter','18"','3','2+','5','-1','2'],['Salvo Launcher','24"','2','2+','10','-2','D3+2'],['Interceptor Lance · melee','Melee','8','2+','8','-2','2']]},
 {name:'Blade Champion',category:'Infantería',photo:'02',page:'108',stats:['8"','7','2+','7','5+','2','4+'],core:'Deep Strike · Leader',rules:['Swift Onslaught: puede repetir tiradas de avance y carga.','Sword of the Throne: marca a una unidad enemiga y mejora sus ataques contra ella.'],composition:'1 Blade Champion',keywords:'INFANTRY · CHARACTER · IMPERIUM',weapons:[['Vaultswords · Behemor','Melee','5','2+','10','-3','4'],['Vaultswords · Hurricanes','Melee','10','2+','6','-2','1'],['Vaultswords · Victus','Melee','8','2+','8','-3','2']]},
 {name:'Sentinel Guard Sodality',category:'Infantería',photo:'02',page:'108',stats:['8"','7','2+','5','5+','3','4+'],core:'Deep Strike',rules:['Stand Vigil: gana impactos letales contra objetivos cerca de un objetivo.','Praesidium Shield: los ataques de fuerza superior reducen su capacidad de herir.','Vexilla: +1 OC y puede ignorar modificadores al liderazgo.'],composition:'3 Sentinel Guard models; una miniatura puede llevar Vexilla.',keywords:'INFANTRY · BATTLELINE · IMPERIUM · TRUSTED SENTINEL',weapons:[['Sentinel Blade · ranged','12"','4','2+','5','-1','2'],['Sentinel Blade · melee','Melee','5','2+','6','-2','2']]},
 {name:'Custodian Guard',category:'Infantería',photo:'03',page:'109',stats:['8"','7','2+','5','5+','3','4+'],core:'Deep Strike',rules:['Impenetrable Defence: puede repetir impactos en ciertas situaciones al disputar objetivos.','Vexilla: +1 OC y puede ignorar modificadores al liderazgo.'],composition:'3 Custodian Guard models; cada modelo lleva Guardian Spear.',keywords:'INFANTRY · BATTLELINE · IMPERIUM · TRUSTED SENTINEL',weapons:[['Guardian Spear · ranged','24"','2','2+','5','-1','2'],['Guardian Spear · melee','Melee','6','2+','8','-2','2']]},
 {name:'Custodian Wardens',category:'Infantería',photo:'03',page:'109',stats:['8"','7','2+','6','5+','2','4+'],core:'Deep Strike',rules:['Living Fortress: los ataques que reciben tienen -1 AP.','Vexilla: +1 OC y puede ignorar modificadores al liderazgo.'],composition:'2–3 Custodian Warden models; cada modelo lleva Guardian Spear.',keywords:'INFANTRY · IMPERIUM · TRUSTED SENTINEL',weapons:[['Castellan Axe · ranged','24"','2','2+','5','-1','2'],['Guardian Spear · ranged','24"','2','2+','5','-1','2'],['Castellan Axe · melee','Melee','3','2+','10','-2','4'],['Guardian Spear · melee','Melee','6','2+','8','-2','2']]},
 {name:'Trajann Valoris',category:'Infantería',photo:'04',page:'106',stats:['8"','7','2+','10','5+','2','4+'],core:'Deep Strike · Feel No Pain 5+ · Leader',rules:['Captain-General: permite repetir unos impactos y heridas a unidades Custodes cercanas.','Moment Shackle: escoge un efecto de combate al inicio de una fase.','Supreme Commander: debe ser el Warlord del ejército.'],composition:'1 Trajann Valoris',keywords:'INFANTRY · CHARACTER · EPIC HERO · IMPERIUM',weapons:[['Eagle’s Scream','24"','2','2+','6','-2','2'],['Watcher’s Axe','Melee','6','2+','12','-3','4']]},
 {name:'Shield-Captain',category:'Infantería',photo:'04',page:'106',stats:['8"','7','2+','8','5+','2','4+'],core:'Deep Strike · Leader',rules:['Master of the Ka’tahs: una vez por ronda, recupera una habilidad de datasheet.','Vengeful Surge: puede hacer un movimiento reactivo tras sufrir bajas.','Praesidium Shield: reduce el daño de los ataques asignados.'],composition:'1 Shield-Captain model',keywords:'INFANTRY · CHARACTER · IMPERIUM · SHIELD-CAPTAIN',weapons:[['Castellan Axe · ranged','24"','2','2+','5','-1','2'],['Guardian Spear · ranged','24"','2','2+','5','-1','2'],['Pyrithe Spear','12"','1','2+','10','-3','D3+2'],['Castellan Axe · melee','Melee','5','2+','10','-2','4'],['Guardian Spear · melee','Melee','8','2+','8','-2','2']]},
 {name:'Aquilon Terminators · Gauntlets',category:'Infantería',photo:'05',page:'111',stats:['7"','8','2+','6','5+','2','4+'],core:'Deep Strike',rules:['Dread Foe: los ataques cuerpo a cuerpo contra unidades que no sean Monster/Vehicle tienen +1 AP.'],composition:'3 Aquilon Terminator models; cada uno lleva Adrathic Combi-destructor y Solarite Power Gauntlet.',keywords:'INFANTRY · IMPERIUM · TERMINATOR',weapons:[['Adrathic Combi-destructor','12"','2','2+','5','-2','3'],['Solarite Power Gauntlet','Melee','5','2+','10','-2','3']]},
 {name:'Aquilon Terminators · Talons',category:'Infantería',photo:'05',page:'111',stats:['7"','8','2+','6','5+','2','4+'],core:'Deep Strike',rules:['Reap a Terrible Tally: repite unos impactos y heridas contra unidades Infantry.'],composition:'3 Aquilon Terminator models; cada uno lleva Lastrum Storm Bolter y Solarite Power Talon.',keywords:'INFANTRY · IMPERIUM · TERMINATOR',weapons:[['Infernus Firepike','12"','3','—','5','-1','1'],['Lastrum Storm Bolter','24"','3','2+','5','-1','1'],['Solarite Power Talon','Melee','6','2+','6','-2','1']]},
 {name:'Venatari · Kinetic Destroyers',category:'Infantería',photo:'06',page:'112',stats:['12"','7','2+','5','5+','2','4+'],core:'Deep Strike',rules:['Take Wing: puede retirarse a reservas estratégicas al final de la fase de combate enemiga.','Neutronium Cascade Mine: puede causar heridas mortales a una unidad cercana.','Strike from the Skies: puede repetir impactos tras entrar desde reservas.'],composition:'3 Venatari models; cada uno lleva Kinetic Destroyer y Tarsus Buckler.',keywords:'INFANTRY · EXPLOSIVES · FLY · IMPERIUM · JUMP PACK',weapons:[['Kinetic Destroyer','18"','4','2+','6','-2','1'],['Tarsus Buckler','Melee','5','2+','6','-2','1']]},
 {name:'Venatari · Verutum Lances',category:'Infantería',photo:'06',page:'112',stats:['12"','7','2+','5','5+','2','4+'],core:'Deep Strike',rules:['Take Wing: puede retirarse a reservas estratégicas al final de la fase de combate enemiga.','Swift Ruin: puede usar Rapid Ingress con coste reducido.'],composition:'3 Venatari models; cada uno lleva Verutum Lance.',keywords:'INFANTRY · EXPLOSIVES · FLY · IMPERIUM · JUMP PACK',weapons:[['Verutum Lance · ranged','18"','1','2+','10','-2','3'],['Verutum Lance · melee','Melee','5','2+','7','-2','2']]},
 {name:'Telemon Heavy Dreadnought',category:'Vehículo',photo:'07',page:'113',stats:['10"','11','2+','14','5+','4','4+'],core:'Damaged 5 · Deadly Demise D3',rules:['Guardian Eternal: los ataques a distancia contra esta unidad tienen -1 daño.','Puede cambiar sus armas pesadas por distintas combinaciones.'],composition:'1 Telemon Heavy Dreadnought',keywords:'VEHICLE · DREADNOUGHT · IMPERIUM · WALKER',weapons:[['Arachnus Storm Cannon','24"','12','2+','6','-1','1'],['Iliastus Accelerator Culverin','48"','3','2+','10','-1','3'],['Spiculus Bolt Launcher','36"','6','2+','5','-1','1'],['Caestus Fist','Melee','5','2+','14','-3','4']]},
 {name:'Contemptor-Galatus Dreadnought',category:'Vehículo',photo:'08',page:'114',stats:['9"','10','2+','12','5+','3','4+'],core:'Damaged 4 · Deadly Demise D3',rules:['Unyielding Ancient: los ataques con fuerza superior reducen su capacidad de herir.'],composition:'1 Contemptor-Galatus Dreadnought; equipado con Warblade.',keywords:'VEHICLE · DREADNOUGHT · IMPERIUM · WALKER',weapons:[['Warblade · ranged','12"','4','—','6','-1','2'],['Warblade · melee','Melee','8','2+','10','-2','3']]},
 {name:'Contemptor-Achillus Dreadnought',category:'Vehículo',photo:'08',page:'114',stats:['9"','10','2+','12','5+','3','5+'],core:'Damaged 4 · Deadly Demise D3',rules:['Unyielding Ancient: los ataques con fuerza superior reducen su capacidad de herir.'],composition:'1 Contemptor-Achillus Dreadnought; equipado con Dreadspear y armamento auxiliar.',keywords:'VEHICLE · DREADNOUGHT · IMPERIUM · WALKER',weapons:[['Adrathic Combi-destructor','12"','2','2+','5','-2','3'],['Dreadspear','18"','2','2+','10','-3','D3+2'],['Dreadspear · melee','Melee','5','2+','12','-3','D3+3']]},
 {name:'Allarus Custodians',category:'Infantería',photo:'09',page:'110',stats:['7"','8','2+','6','5+','2','4+'],core:'Deep Strike',rules:['Slayer of Tyrants: bonificación para herir en combate contra unidades de mayor resistencia.','Vexilla: +1 OC y puede ignorar modificadores al liderazgo.'],composition:'2–3 Allarus Custodian models.',keywords:'INFANTRY · IMPERIUM · TERMINATOR',weapons:[['Ballistus Grenade Launcher','18"','3','2+','5','-1','1'],['Castellan Axe · melee','Melee','3','2+','10','-2','4'],['Guardian Spear · melee','Melee','6','2+','8','-2','2']]},
 {name:'Pallas Grav-Attack',category:'Vehículo',photo:'24',page:'116',stats:['12"','9','2+','10','5+','2','5+'],core:'Deadly Demise 1 · Deep Strike',rules:['Mobile Hunter: después de disparar puede hacer un movimiento normal; no puede cargar ese turno.'],composition:'1 Pallas Grav-attack model',keywords:'VEHICLE · FLY · FRAME · GRAV-ASSAULT · IMPERIUM',weapons:[['Twin Arachnus Blaze Cannon','24"','2','2+','10','-3','D3+2'],['Twin Iliastus Accelerator Fusil','48"','2','2+','10','-1','3'],['Armoured Hull','Melee','3','4+','6','0','1']]},
 {name:'Coronus Grav-Carrier',category:'Vehículo',photo:'24',page:'116',stats:['12"','12','2+','16','5+','5','5+'],core:'Damaged 6 · Deadly Demise D6 · Deep Strike',rules:['Repulsor Suspensor Technology: tras recibir fuego puede moverse si está desenganchado.','Assault Vehicle: las unidades embarcadas pueden desembarcar tras avanzar.','Transport: capacidad para 5 modelos Adeptus Custodes Infantry.'],composition:'1 Coronus Grav-carrier model',keywords:'VEHICLE · FLY · FRAME · GRAV-ASSAULT · IMPERIUM · TRANSPORT',weapons:[['Twin Arachnus Blaze Cannon','24"','2','2+','10','-3','D3+2'],['Twin Lastrum Bolt Cannon','36"','3','2+','6','-2','2'],['Twin Neutronium Cascade Projectors','12"','3','—','7','-2','1'],['Armoured Hull','Melee','6','4+','8','0','1']]},
 {name:'Caladius Grav-Tank',category:'Vehículo',photo:'25',page:'117',stats:['10"','11','2+','14','5+','4','5+'],core:'Damaged 5 · Deadly Demise D3 · Deep Strike',rules:['Destructor Optics: los ataques a distancia contra objetivos que no sean Monster/Vehicle tienen +1 AP.'],composition:'1 Caladius Grav-tank model',keywords:'VEHICLE · CALADIUS · FLY · FRAME · GRAV-ASSAULT · IMPERIUM',weapons:[['Illiastus Accelerator Cannon','48"','4','2+','10','-1','3'],['Twin Lastrum Bolt Cannon','36"','3','2+','6','-2','2'],['Twin Neutronium Cascade Projectors','12"','3','—','7','-2','1'],['Armoured Hull','Melee','4','4+','6','0','1']]},
 {name:'Caladius Annihilator Grav-Tank',category:'Vehículo',photo:'25',page:'117',stats:['10"','11','2+','14','5+','4','5+'],core:'Damaged 5 · Deadly Demise D3 · Deep Strike',rules:['Advanced Firepower: contra objetivos Monster/Vehicle puede repetir una tirada de impacto, herida y daño.'],composition:'1 Caladius Annihilator Grav-tank model',keywords:'VEHICLE · CALADIUS · FLY · FRAME · GRAV-ASSAULT · IMPERIUM',weapons:[['Arachnus Blaze Carronade','48"','4','2+','12','-3','D6+2'],['Twin Lastrum Bolt Cannon','36"','3','2+','6','-2','2'],['Twin Neutronium Cascade Projectors','12"','3','—','7','-2','1'],['Armoured Hull','Melee','4','4+','6','0','1']]},
 {name:'Knight-Centura',category:'Hermanas del Silencio',photo:'26',page:'—',stats:['7"','3','3+','4','6+','1','5+'],core:'Scout 7" · Support',rules:['Seeker’s Instincts: +2" al movimiento y puede repetir avances y cargas.','Corner the Quarry: dificulta la retirada de enemigos trabados.'],composition:'1 Knight-Centura model',keywords:'INFANTRY · ANATHEMA PSYKANA · CHARACTER · IMPERIUM',weapons:[['Master-crafted Boltgun','24"','2','2+','5','-1','2'],['Master-crafted Flamer','12"','4','—','4','-1','1'],['Executioner Greatblade','Melee','4','2+','5','-2','2']]},
 {name:'Prosecutor Squad',category:'Hermanas del Silencio',photo:'26',page:'—',stats:['7"','3','3+','1','6+','2','—'],core:'—',rules:['Purity of Execution: detecta una unidad enemiga visible cercana y amplía su rango de detección.'],composition:'4–10 Prosecutor models; cada modelo lleva Boltgun y Gun Stock.',keywords:'INFANTRY · ANATHEMA PSYKANA · IMPERIUM',weapons:[['Boltgun','24"','1','3+','5','-1','1'],['Gun Stock · melee','Melee','2','3+','3','0','1']]},
 {name:'Vigilator Squad',category:'Hermanas del Silencio',photo:'27',page:'—',stats:['7"','3','3+','1','6+','1','—'],core:'—',rules:['Deft Parry: los ataques cuerpo a cuerpo contra esta unidad tienen -1 a impactar.'],composition:'4–10 Vigilator models; cada modelo lleva Executioner Greatblade.',keywords:'INFANTRY · ANATHEMA PSYKANA · IMPERIUM',weapons:[['Executioner Greatblade','Melee','3','3+','5','-2','2']]}
];

const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function renderPointsBadge(u){
  const points=getUnitPoints(u), models=points.options?.filter(option=>option.models).map(option=>option.models);
  const context=points.status==='missing'?'Sin coste en la tabla':points.status==='increase'?'Rumor · total por confirmar':points.status==='uncertain'?'Rumor · variante por confirmar':models?.length?`Rumor · ${models.join(' / ')} miniaturas`:'Rumor';
  return `<div class="unit-points ${points.status==='missing'?'is-missing':''}"><b>${esc(pointsSummary(points))}</b><span>${esc(context)}</span></div>`;
}
function renderPointsDetail(u){
  const points=getUnitPoints(u);
  const costs=points.options?.map(option=>`<li><span>${esc(option.models?`${option.models} miniaturas`:option.label||'Unidad')}</span><strong>${esc(option.points)} pts</strong></li>`).join('');
  return `<section class="sheet-points" aria-label="Coste en puntos"><div class="points-heading"><h3>Coste en puntos</h3><span>${points.status==='missing'?'Por confirmar':'Rumoreado'}</span></div>${costs?`<ul class="points-options">${costs}</ul>`:`<p class="points-pending">${esc(pointsSummary(points))}${points.status==='increase'?' · total por confirmar':''}</p>`}${points.note?`<p class="points-note">${esc(points.note)}</p>`:''}<p class="points-source">Fuente: tabla de puntos reenviada, facilitada el 02/10/2026. Valores sin confirmación oficial.</p></section>`;
}
function renderUnits(){const query=norm($('#unitSearch').value.trim()),cat=$('#unitCategory').value;const list=units.filter(u=>(cat==='all'||u.category===cat)&&(!query||norm(JSON.stringify(u)).includes(query)));$('#unitCount').textContent=units.length;$('#unitResults').textContent=`${list.length} ${list.length===1?'resultado':'resultados'}`;$('#unitEmpty').hidden=!!list.length;$('#unitGrid').innerHTML=list.map((u,i)=>`<button class="unit-card" data-index="${units.indexOf(u)}"><div class="unit-image"><img src="images/${u.photo}.jpeg" alt=""><span>${esc(u.category)}</span></div><div class="unit-card-body"><small>FOTO ${u.photo} · PÁG. ${esc(u.page)}</small><h2>${esc(u.name)}</h2>${renderPointsBadge(u)}<div class="mini-stats">${['M','T','SV','W','LD','OC','INV'].map((k,n)=>`<span><i>${k}</i><b>${esc(u.stats[n])}</b></span>`).join('')}</div><p>${esc(u.weapons.slice(0,2).map(w=>w[0]).join(' · '))}</p><div class="unit-link">ABRIR FICHA <b>＋</b></div></div></button>`).join('');$('#unitGrid').querySelectorAll('.unit-card').forEach(b=>b.onclick=()=>openUnit(units[Number(b.dataset.index)]))}
function openUnit(u){const img=`images/${u.photo}.jpeg`;$('#sheetContent').innerHTML=`<div class="sheet-top"><div><div class="eyebrow">ADEPTUS CUSTODES · FOTO ${u.photo} · PÁG. ${esc(u.page)}</div><h2>${esc(u.name)}</h2></div><button class="icon-button" id="closeSheet" aria-label="Cerrar">×</button></div>${renderPointsDetail(u)}<div class="sheet-hero"><img src="${img}" alt="Foto de referencia de ${esc(u.name)}"><div class="stats-grid">${['M','T','SV','W','LD','OC','Invulnerable'].map((k,i)=>`<div><span>${k}</span><b>${esc(u.stats[i])}</b></div>`).join('')}</div></div><div class="sheet-two"><section><h3>Armas a distancia y cuerpo a cuerpo</h3><div class="weapon-table"><div class="weapon-row weapon-head"><span>Arma</span><span>Rango</span><span>A</span><span>HA/HP</span><span>F</span><span>AP</span><span>D</span></div>${u.weapons.map(w=>`<div class="weapon-row"><strong>${esc(w[0])}</strong><span>${esc(w[1])}</span><span>${esc(w[2])}</span><span>${esc(w[3])}</span><span>${esc(w[4])}</span><span>${esc(w[5])}</span><span>${esc(w[6])}</span></div>`).join('')}</div><h3>Composición de la unidad</h3><p class="sheet-copy">${esc(u.composition)}</p></section><section><h3>Habilidades</h3><div class="ability-box"><b>Habilidades básicas</b><p>${esc(u.core)}</p></div>${u.rules.map((r,i)=>`<div class="ability-box"><b>${i===0?'Regla de unidad':'Habilidad'}</b><p>${esc(r)}</p></div>`).join('')}<h3>Palabras clave</h3><p class="keywords">${esc(u.keywords)}</p><h3>Fuente</h3><a class="source-photo" href="${img}" target="_blank" rel="noreferrer">Abrir foto original · ${u.photo}.jpeg</a></section></div><details class="ocr-source"><summary>Ver OCR completo de esta página</summary><pre id="pageOcr">Cargando transcripción OCR…</pre></details>`;$('#closeSheet').onclick=()=>$('#sheetDialog').close();$('#sheetDialog').showModal();fetch('/api/ocr').then(r=>r.json()).then(data=>$('#pageOcr').textContent=data[u.photo]||'No hay transcripción OCR guardada para esta foto.').catch(()=>$('#pageOcr').textContent='No se pudo cargar el texto OCR guardado.')}
$('#unitSearch').addEventListener('input',renderUnits);$('#unitCategory').addEventListener('change',renderUnits);document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('#unitSearch').focus()}if(e.key==='Escape')$('#sheetDialog').close()});renderUnits();
